const denave = [
  {
    Firmographics: "Startup",
    entity_name: "captain tractors pvt. ltd.",
    Company_Size: "201-500",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.captaintractors.com",
    company_linkedin_url: "https://in.linkedin.com/company/captaintractors",
    cleaned_boardline_number:
      "'+919033905500 / +912827252547 / +919228018432 / +919909905590 / +919726499966 / +917486032602 / +919099433133 / +919898460090 / +919726270707 / +919033033134",
    branch_type: "branch office",
    address:
      "By Mail : Captain Tractors Pvt. Ltd., Padavla Road, Veraval ( Shapar ), Taluka : Kotda Sangani, Dist. Rajkot ( Gujarat ) India. Pincode : 360024.",
    City: "veraval",
    State: "gujarat",
    zip_code: 360024,
    Country: "india",
    contact_name: "Mayur Sakhiya",
    job_title: "software engineer",
    Department: "information technology",
    Seniority_Level: "junior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/mayur-sakhiya-0b9385a7",
    phone_number: 5229346418,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "cybage software pvt ltd",
    Company_Size: "5001-10000",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.cybage.com",
    company_linkedin_url: "https://www.linkedin.com/company/cybage",
    cleaned_boardline_number: "'+912066041700",
    branch_type: "headquarters",
    address:
      "Cybage Towers Survey No 13A / 1 + 2 + 3 / 1 Wadgaon Sheri Pune, Maharashtra - 411014",
    City: "pune",
    State: "maharashtra",
    zip_code: 411014,
    Country: "india",
    contact_name: "Shailendra Kumbhar",
    job_title: "software engineer",
    Department: "information technology",
    Seniority_Level: "junior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/shailendra-kumbhar-7202a54",
    phone_number: 4110682418,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "dantal hydrolic pvt. ltd",
    Company_Size: "201-500",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.dantal.in",
    company_linkedin_url:
      "https://in.linkedin.com/company/dantal-hydraulics-pvt.-ltd",
    cleaned_boardline_number: "'+911244586804 / +911244369414 / +911244581800",
    branch_type: "headquarters",
    address:
      "Dantal Hydraulics Pvt. Ltd 24, Udyog Vihar, Phase Iv, Gurgaon, Haryana - 122015 ( India )",
    City: "gurugram",
    State: "haryana",
    zip_code: 122015,
    Country: "india",
    contact_name: "Abrar Ahmed",
    job_title: "team lead - intellectual property analytics",
    Department: "information technology",
    Seniority_Level: "junior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/abrar-ahmed-02a3394",
    phone_number: 8656330693,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "dq entertainment (int.) pvt. ltd.",
    Company_Size: "1001-5000",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.dqentertainment.com",
    company_linkedin_url: "https://in.linkedin.com/company/dq-entertainment",
    cleaned_boardline_number: "'+914023552594 / +914023553726",
    branch_type: "single location",
    address:
      "Address Dq Entertainment International Limited 644, Aurora Colony, Road No 3, Banjara Hills, Hyderabad - 500034, Telangana, India",
    City: "hyderabad",
    State: "telangana",
    zip_code: 500034,
    Country: "india",
    contact_name: "Satya INV",
    job_title: "lead - security",
    Department: "information technology",
    Seniority_Level: "junior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/satya-inv-97751b47",
    phone_number: 6681201462,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "dq entertainment (int.) pvt. ltd.",
    Company_Size: "1001-5000",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.dqentertainment.com",
    company_linkedin_url: "https://in.linkedin.com/company/dq-entertainment",
    cleaned_boardline_number: "'+914023552594 / +914023553726",
    branch_type: "single location",
    address:
      "Address Dq Entertainment International Limited 644, Aurora Colony, Road No 3, Banjara Hills, Hyderabad - 500034, Telangana, India",
    City: "hyderabad",
    State: "telangana",
    zip_code: 500034,
    Country: "india",
    contact_name: "pavan vedantam",
    job_title: "executive - marketing",
    Department: "marketing & communications",
    Seniority_Level: "junior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/pavan-vedantam-5539219b",
    phone_number: 5807786307,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "dq entertainment (int.) pvt. ltd.",
    Company_Size: "1001-5000",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.dqentertainment.com",
    company_linkedin_url: "https://in.linkedin.com/company/dq-entertainment",
    cleaned_boardline_number: "'+914023552594 / +914023553726",
    branch_type: "single location",
    address:
      "Address Dq Entertainment International Limited 644, Aurora Colony, Road No 3, Banjara Hills, Hyderabad - 500034, Telangana, India",
    City: "hyderabad",
    State: "telangana",
    zip_code: 500034,
    Country: "india",
    contact_name: "Ganesh N",
    job_title: "executive - marketing",
    Department: "marketing & communications",
    Seniority_Level: "junior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/ganesh-n-340931aa",
    phone_number: 9331291726,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "essae digitronics pvt ltd.",
    Company_Size: "1001-5000",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.essaedig.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/essae-digitronics-pvt-ltd",
    cleaned_boardline_number:
      "'+919379251425 / +919343137723 / +919513210029 / +919513632081 / +919342332374 / +919379251413 / +919342892103",
    branch_type: "branch office",
    address:
      "Essae Digitronics Pvt Ltd Plot No - 43, Bommasandra Industrial Area, Anekal Taluk, Bommasandra, Bangalore - 560099",
    City: "bengaluru",
    State: "karnataka",
    zip_code: 560099,
    Country: "india",
    contact_name: "Praveen AR",
    job_title: "manager - local",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "praveen.ar@essaedig.com",
    linkedin_id: "https://in.linkedin.com/in/praveen-a-r-88637b1b",
    phone_number: 4162014260,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "essae digitronics pvt ltd.",
    Company_Size: "1001-5000",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.essaedig.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/essae-digitronics-pvt-ltd",
    cleaned_boardline_number:
      "'+919379251425 / +919343137723 / +919513210029 / +919513632081 / +919342332374 / +919379251413 / +919342892103",
    branch_type: "branch office",
    address:
      "Essae Digitronics Pvt Ltd Plot No - 43, Bommasandra Industrial Area, Anekal Taluk, Bommasandra, Bangalore - 560099",
    City: "bengaluru",
    State: "karnataka",
    zip_code: 560099,
    Country: "india",
    contact_name: "Arjun HN",
    job_title: "manager - product",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/arjun-hn-bb126a67",
    phone_number: 6377561694,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "g. m. engineering pvt. ltd.",
    Company_Size: "201-500",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.gmengg.com",
    company_linkedin_url: "https://in.linkedin.com/company/gmengg",
    cleaned_boardline_number:
      "'+919227655582 / +919228005559 / +919099085054 / +912827287857 / +919227655581 / +912827287658 / +919228005556 / +919228005558",
    branch_type: "branch office",
    address:
      "G M Engineering Private Limited Plot No 2632, G. I. D. C. Lodhika, Village Metoda, Rajkot 360021 Gujarat [ India ]",
    City: "rajkot",
    State: "gujarat",
    zip_code: 360021,
    Country: "uk",
    contact_name: "Megh Patel",
    job_title: "manager - product",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/megh-patel-a51a7268",
    phone_number: 3965342325,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "k2 india pvt. ltd.",
    Company_Size: "5001-10000",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.k2cranes.com",
    company_linkedin_url: "https://in.linkedin.com/company/k2-group-india",
    cleaned_boardline_number:
      "'+919176940707 / +914448588100 / +919884033365 / +919884902896 / +919884300490",
    branch_type: "headquarters",
    address:
      "Visit Us : # 14 - A, Telugu Brahmin Street, Velachery, Chennai - 600042. India.",
    City: "chennai",
    State: "tamilnadu",
    zip_code: 600042,
    Country: "india",
    contact_name: "Rupendra M Anklekar",
    job_title: "director - technical",
    Department: "information technology",
    Seniority_Level: "executive management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/dr-rupendra-m-anklekar-b2b4b233",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "larsen and toubro pvt ltd",
    Company_Size: "10001 & above",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.larsentoubro.com",
    company_linkedin_url: "https://in.linkedin.com/company/larsen-",
    cleaned_boardline_number:
      "'+911414385900 / +918472301058 / +918607246000 / +911414385925",
    branch_type: "branch office",
    address:
      "Monarch Building, 1St Floor, D - 236 & 237, Amrapali Marg, Vaishali Nagar, Jaipur 302021",
    City: "jaipur",
    State: "rajasthan",
    zip_code: 302021,
    Country: "india",
    contact_name: "Umesh Kulkarni",
    job_title: "functional consultant",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/umesh-kulkarni-9a247b7",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "lupin pvt ltd.",
    Company_Size: "10001 & above",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.lupin.com",
    company_linkedin_url: "https://www.linkedin.com/company/lupin",
    cleaned_boardline_number: "'+912266402323 / +912266402051",
    branch_type: "headquarters",
    address:
      "Corporate Office Lupin Limited, 3Rd Floor, Kalpataru Inspire, Off. Western Expressway Highway, Santacruz ( East ), Mumbai 400055, India.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400055,
    Country: "india",
    contact_name: "Vinayak Rao",
    job_title: "senior product manager",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/vinayak-rao-aa53091a",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "lupin pvt ltd.",
    Company_Size: "10001 & above",
    Industry: "",
    Sub_Industry: "",
    activity_type: "",
    website: "http://www.lupin.com",
    company_linkedin_url: "https://www.linkedin.com/company/lupin",
    cleaned_boardline_number: "'+912266402323 / +912266402051",
    branch_type: "headquarters",
    address:
      "Corporate Office Lupin Limited, 3Rd Floor, Kalpataru Inspire, Off. Western Expressway Highway, Santacruz ( East ), Mumbai 400055, India.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400055,
    Country: "india",
    contact_name: "Kamlesh Patel",
    job_title: "head - medical & health technology",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/dr-kamlesh-patel-3241b12",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Public Listing",
    entity_name: "lupin pvt ltd.",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.lupin.com",
    company_linkedin_url: "https://www.linkedin.com/company/lupin",
    cleaned_boardline_number: "'+912266402323 / +912266402051",
    branch_type: "headquarters",
    address:
      "Corporate Office Lupin Limited, 3Rd Floor, Kalpataru Inspire, Off. Western Expressway Highway, Santacruz ( East ), Mumbai 400055, India.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400055,
    Country: "uk",
    contact_name: "Sanjiv Jha",
    job_title: "deputy general manager - information technology",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/sanjiv-jha-ab367629",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "lupin pvt ltd.",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.lupin.com",
    company_linkedin_url: "https://www.linkedin.com/company/lupin",
    cleaned_boardline_number: "'+912266402323 / +912266402051",
    branch_type: "headquarters",
    address:
      "Corporate Office Lupin Limited, 3Rd Floor, Kalpataru Inspire, Off. Western Expressway Highway, Santacruz ( East ), Mumbai 400055, India.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400055,
    Country: "india",
    contact_name: "Arun Venkat",
    job_title: "manager - travel (corporate)",
    Department: "marketing & communications",
    Seniority_Level: "middle management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/arun-venkat-5b075a30",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "lupin pvt ltd.",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.lupin.com",
    company_linkedin_url: "https://www.linkedin.com/company/lupin",
    cleaned_boardline_number: "'+912266402323 / +912266402051",
    branch_type: "headquarters",
    address:
      "Corporate Office Lupin Limited, 3Rd Floor, Kalpataru Inspire, Off. Western Expressway Highway, Santacruz ( East ), Mumbai 400055, India.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400055,
    Country: "india",
    contact_name: "Sanjay Moolchandani",
    job_title: "senior vice president - application program interface (global)",
    Department: "information technology",
    Seniority_Level: "executive management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/sanjay-moolchandani-2b91752b",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "m. p. m. private limited",
    Company_Size: "201-500",
    Industry: "chemicals",
    Sub_Industry: "Other Organic & Inorganic Chemicals",
    activity_type: "Manufacturing",
    website: "http://www.mpmindia.com",
    company_linkedin_url: "https://in.linkedin.com/company/mpmindia",
    cleaned_boardline_number:
      "'+917104232401 / +917104232402 / +917104237065 / +919890333027",
    branch_type: "branch office",
    address: "M - 22, Midc, Hingna Industrial Estate, Nagpur - 440016 India",
    City: "nagpur",
    State: "maharashtra",
    zip_code: 440016,
    Country: "india",
    contact_name: "ashish mandaogade",
    job_title: "senior manager - information technology (sap)",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/ashish-mandaogade-a8799024",
    phone_number: "",
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "m. p. m. private limited",
    Company_Size: "201-500",
    Industry: "chemicals",
    Sub_Industry: "Other Organic & Inorganic Chemicals",
    activity_type: "Manufacturing",
    website: "http://www.mpmindia.com",
    company_linkedin_url: "https://in.linkedin.com/company/mpmindia",
    cleaned_boardline_number:
      "'+917104232401 / +917104232402 / +917104237065 / +919890333027",
    branch_type: "branch office",
    address: "M - 22, Midc, Hingna Industrial Estate, Nagpur - 440016 India",
    City: "nagpur",
    State: "maharashtra",
    zip_code: 440016,
    Country: "india",
    contact_name: "Jayant Patankar",
    job_title: "advisor - technical services",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/jayant-patankar-4a99901b9",
    phone_number: 1987647650,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "manipal global education service pvt ltd",
    Company_Size: "1001-5000",
    Industry: "education & training",
    Sub_Industry: "training & testing",
    activity_type: "Service Provider",
    website: "http://www.manipalglobal.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/manipal-global-education-services",
    cleaned_boardline_number: "'+918040789100",
    branch_type: "branch office",
    address:
      "Unext Learning Private Limited Manipal Towers, 14 Hal Airport Road, Bengaluru - 560008",
    City: "bengaluru",
    State: "karnataka",
    zip_code: 560008,
    Country: "india",
    contact_name: "Aparna Ghosh",
    job_title: "head (content)",
    Department: "marketing & communications",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/aparna-ghosh-aa26588",
    phone_number: 2814873982,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "manipal global education service pvt ltd",
    Company_Size: "1001-5000",
    Industry: "education & training",
    Sub_Industry: "training & testing",
    activity_type: "Service Provider",
    website: "http://www.manipalglobal.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/manipal-global-education-services",
    cleaned_boardline_number: "'+918040789100",
    branch_type: "branch office",
    address:
      "Unext Learning Private Limited Manipal Towers, 14 Hal Airport Road, Bengaluru - 560008",
    City: "bengaluru",
    State: "karnataka",
    zip_code: 560008,
    Country: "india",
    contact_name: "nikhil verma",
    job_title: "head - local",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/nikhil-verma-b9456047",
    phone_number: 1896844393,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "nms works software private limited",
    Company_Size: "201-500",
    Industry: "it & communication",
    Sub_Industry: "it enabled services",
    activity_type: "Service Provider",
    website: "http://www.nmsworks.co.in",
    company_linkedin_url: "https://in.linkedin.com/company/nmsworks",
    cleaned_boardline_number: "'+914466630608 / +914466469881 / +914466630606",
    branch_type: "single location",
    address:
      "Headquaters # C3, 6Th Floor, Iit Madras Research Park, Taramani, Chennai - 600113, Tamil Nadu, India",
    City: "chennai",
    State: "tamilnadu",
    zip_code: 600113,
    Country: "india",
    contact_name: "Ajit Dash",
    job_title: "senior manager - software",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/ajit-dash-aa344256",
    phone_number: 4169705315,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "nms works software private limited",
    Company_Size: "201-500",
    Industry: "it & communication",
    Sub_Industry: "it enabled services",
    activity_type: "Service Provider",
    website: "http://www.nmsworks.co.in",
    company_linkedin_url: "https://in.linkedin.com/company/nmsworks",
    cleaned_boardline_number: "'+914466630608 / +914466469881 / +914466630606",
    branch_type: "single location",
    address:
      "Headquaters # C3, 6Th Floor, Iit Madras Research Park, Taramani, Chennai - 600113, Tamil Nadu, India",
    City: "chennai",
    State: "tamilnadu",
    zip_code: 600113,
    Country: "india",
    contact_name: "Jyoti Purohit",
    job_title: "consultant - technical",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "",
    linkedin_id: "https://in.linkedin.com/in/jyoti-purohit-956a314",
    phone_number: 2359984269,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "ntf (india) pvt ltd",
    Company_Size: "1001-5000",
    Industry: "automotive",
    Sub_Industry: "automotive",
    activity_type: "Manufacturing",
    website: "http://www.ntfholding.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/ntfholding https://in.linkedin.com/company/ntf-technik-india-pvt.-ltd. https://in.linkedin.com/in/naveen-jain-5431086",
    cleaned_boardline_number: "'+911244415118",
    branch_type: "headquarters",
    address:
      "Corporate Head Office 49, Sector - 3, Imt Manesar, Gurugram - 122050 Haryana. India P :  E :",
    City: "gurugram",
    State: "haryana",
    zip_code: "",
    Country: "india",
    contact_name: "Kanti Kumar",
    job_title: "senior general manager - information technology (corporation)",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "kanti.kumar@ntfholding.com",
    linkedin_id: "https://in.linkedin.com/in/kanti-kumar-27107b5",
    phone_number: "",
    profiling_status: "STD",
  },
  {
    Firmographics: "Startup",
    entity_name: "ntf (india) pvt ltd",
    Company_Size: "1001-5000",
    Industry: "automotive",
    Sub_Industry: "automotive",
    activity_type: "Manufacturing",
    website: "http://www.ntfholding.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/ntfholding https://in.linkedin.com/company/ntf-technik-india-pvt.-ltd. https://in.linkedin.com/in/naveen-jain-5431086",
    cleaned_boardline_number: "'+911244415118",
    branch_type: "headquarters",
    address:
      "Corporate Head Office 49, Sector - 3, Imt Manesar, Gurugram - 122050 Haryana. India P :  E :",
    City: "gurugram",
    State: "haryana",
    zip_code: "",
    Country: "india",
    contact_name: "Kanti Kumar",
    job_title: "general manager - information technology (corporation)",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "kanti.kumar@ntfholding.com",
    linkedin_id: "https://in.linkedin.com/in/kanti-kumar-042a89a",
    phone_number: "",
    profiling_status: "STD",
  },
  {
    Firmographics: "Startup",
    entity_name: "om telecom logistics pvt ltd",
    Company_Size: "5001-10000",
    Industry: "logistics & transportation",
    Sub_Industry: "warehousing & storage",
    activity_type: "Service Provider",
    website: "http://www.omtelecom.co.in",
    company_linkedin_url:
      "https://in.linkedin.com/company/om-telecom-logistics-pvt-ltd https://in.linkedin.com/in/om-telecom-logistics-863651167",
    cleaned_boardline_number: "'+919312505413 / +919711879548 / +911143799400",
    branch_type: "branch office",
    address:
      "Get In Touch. 159, Punjabi Bagh ( T. C ) Ring Road, New Delhi - 110035, India",
    City: "new delhi",
    State: "delhi",
    zip_code: 110035,
    Country: "india",
    contact_name: "manish singh",
    job_title:
      "in-charge - management information system management information system",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "manish.singh@omtelecom.co.in",
    linkedin_id: "https://in.linkedin.com/in/manish-singh-95171064",
    phone_number: "",
    profiling_status: "STD",
  },
  {
    Firmographics: "Startup",
    entity_name: "paras buildtech india pvt ltd",
    Company_Size: "",
    Industry: "Construction & Real Estate",
    Sub_Industry: "Real Estate",
    activity_type: "Building",
    website: "http://www.parasbuildtech.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/the-parasbuildtech-group",
    cleaned_boardline_number:
      "'+919560097887 / +917669955131 / +911244561500 / +918095072072",
    branch_type: "single location",
    address:
      "Paras Buildtech India Pvt. Ltd. 11Th Floor, Paras Twin Towers ( Tower B ) Sec - 54, Golf Course Road, Gurgaon - 122002, Haryana, India",
    City: "gurugram",
    State: "haryana",
    zip_code: 122002,
    Country: "india",
    contact_name: "Poulomi Ray",
    job_title: "head (marketing)",
    Department: "marketing & communications",
    Seniority_Level: "senior management",
    email_id: "poulomi.ray@parasbuildtech.com",
    linkedin_id: "https://in.linkedin.com/in/poulomi-ray-9a942321",
    phone_number: 6935312209,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "rodic consultants pvt. ltd.",
    Company_Size: "",
    Industry: "Professional Services",
    Sub_Industry: "Management consulting",
    activity_type: "Service Provider",
    website: "http://www.rodicconsultants.com",
    company_linkedin_url: "https://in.linkedin.com/company/rodicconsultants",
    cleaned_boardline_number: "'+911149434500",
    branch_type: "headquarters",
    address:
      "Corporate Office : Rodic Consultants Pvt Ltd 1, Jai Singh Road, New Delhi 110001 ( India )",
    City: "new delhi",
    State: "delhi",
    zip_code: 110001,
    Country: "india",
    contact_name: "sujay darad",
    job_title: "manager - information technology",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "sujay.darad@rodicconsultants.com",
    linkedin_id: "https://in.linkedin.com/in/sujay-darad-b17a0b39",
    phone_number: 6612883051,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "rodic consultants pvt. ltd.",
    Company_Size: "",
    Industry: "Professional Services",
    Sub_Industry: "Management consulting",
    activity_type: "Service Provider",
    website: "http://www.rodicconsultants.com",
    company_linkedin_url: "https://in.linkedin.com/company/rodicconsultants",
    cleaned_boardline_number: "'+911149434500",
    branch_type: "headquarters",
    address:
      "Corporate Office : Rodic Consultants Pvt Ltd 1, Jai Singh Road, New Delhi 110001 ( India )",
    City: "new delhi",
    State: "delhi",
    zip_code: 110001,
    Country: "india",
    contact_name: "Vineet Sachan",
    job_title: "manager - information technology",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "vineet.sachan@rodicconsultants.com",
    linkedin_id: "https://in.linkedin.com/in/vineet-sachan-58598b39",
    phone_number: 4231275969,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "rodic consultants pvt. ltd.",
    Company_Size: "",
    Industry: "Professional Services",
    Sub_Industry: "Management consulting",
    activity_type: "Service Provider",
    website: "http://www.rodicconsultants.com",
    company_linkedin_url: "https://in.linkedin.com/company/rodicconsultants",
    cleaned_boardline_number: "'+911149434500",
    branch_type: "headquarters",
    address:
      "Corporate Office : Rodic Consultants Pvt Ltd 1, Jai Singh Road, New Delhi 110001 ( India )",
    City: "new delhi",
    State: "delhi",
    zip_code: 110001,
    Country: "india",
    contact_name: "devraj tripathi",
    job_title: "manager - information technology",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "devraj.tripathi@rodicconsultants.com",
    linkedin_id: "https://in.linkedin.com/in/devraj-tripathi-12011196",
    phone_number: 4695321732,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "rodic consultants pvt. ltd.",
    Company_Size: "",
    Industry: "Professional Services",
    Sub_Industry: "Management consulting",
    activity_type: "Service Provider",
    website: "http://www.rodicconsultants.com",
    company_linkedin_url: "https://in.linkedin.com/company/rodicconsultants",
    cleaned_boardline_number: "'+911149434500",
    branch_type: "headquarters",
    address:
      "Corporate Office : Rodic Consultants Pvt Ltd 1, Jai Singh Road, New Delhi 110001 ( India )",
    City: "new delhi",
    State: "delhi",
    zip_code: 110001,
    Country: "india",
    contact_name: "Ajit Kumar",
    job_title: "general manager - information technology",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "ajit.kumar@rodicconsultants.com",
    linkedin_id: "https://in.linkedin.com/in/ajit-kumar-956b0911",
    phone_number: 7388386446,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "sanjivani pvt ltd",
    Company_Size: "201-500",
    Industry: "consumer goods",
    Sub_Industry: "fmcg",
    activity_type: "Service Provider",
    website: "http://www.sanjivanicasting.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/sanjivani-tea-private-limited",
    cleaned_boardline_number: "'+919825219405 / +919825225409",
    branch_type: "branch office",
    address:
      "Survey No. 164, Gondal N / H - 27, Sidc Road, Veraval ( Shapar ), Tal. Kotda Sangani, Dist. Rajkot ( Gujarat ) India - 360024",
    City: "veraval",
    State: "gujarat",
    zip_code: 360024,
    Country: "india",
    contact_name: "Ketan Dhruv",
    job_title: "director - marketing",
    Department: "marketing & communications",
    Seniority_Level: "executive management",
    email_id: "ketan.dhruv@sanjivanicasting.com",
    linkedin_id: "https://in.linkedin.com/in/ketan-dhruv-83a430112",
    phone_number: "",
    profiling_status: "STD",
  },
  {
    Firmographics: "Startup",
    entity_name: "senapathy whitely pvt ltd",
    Company_Size: "201-500",
    Industry: "Electronics & Electrical",
    Sub_Industry: "Electrical Equipments & Components",
    activity_type: "Manufacturing",
    website: "http://www.senapathy.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/senapathy-whiteley-pvt-ltd",
    cleaned_boardline_number: "'+918025593307 / +918025593145 / +918025593291",
    branch_type: "single location",
    address:
      'Registered Office" Casa Fina" No - 5, Primrose Road Bangalore - 560025 India.',
    City: "bengaluru",
    State: "karnataka",
    zip_code: 560025,
    Country: "india",
    contact_name: "KS Sajeesh",
    job_title: "consultant - information technology",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "ks.sajeesh@senapathy.com",
    linkedin_id: "https://in.linkedin.com/in/k-s-sajeesh-11879718",
    phone_number: 1313414985,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Startup",
    entity_name: "system engitech pvt. ltd.",
    Company_Size: "201-500",
    Industry: "heavy & industrial machinery",
    Sub_Industry: "industrial machinery",
    activity_type: "Manufacturing",
    website: "http://www.systemengitech.com",
    company_linkedin_url: "https://in.linkedin.com/company/systemengitech",
    cleaned_boardline_number: "'+919727841929 / +919925341929",
    branch_type: "headquarters",
    address:
      "Plot No. 4311 / C, Road No. 4, Near Sagar Hotel, Sachin Gidc, Surat - 394230, Gujarat, India",
    City: "surat",
    State: "gujarat",
    zip_code: 394230,
    Country: "india",
    contact_name: "Ronak Prajapati",
    job_title: "head (unit)",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "ronak.prajapati@systemengitech.com",
    linkedin_id: "https://in.linkedin.com/in/ronak-prajapati-22700918b",
    phone_number: 6544850949,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Startup",
    entity_name: "tarsons product pvt ltd",
    Company_Size: "201-500",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Biotechnology",
    activity_type: "Service Provider",
    website: "http://www.tarsons.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/tarsons-products-ltd",
    cleaned_boardline_number: "'+913335220300 / +919830046084",
    branch_type: "headquarters",
    address:
      "Global Headquarter 902, Martin Burn Business Park, Bp - 3, Saltlake, Sector - V, Kolkata - 700091",
    City: "kolkata",
    State: "westbengal",
    zip_code: 700091,
    Country: "india",
    contact_name: "Avijit Rakshit",
    job_title: "head - information technology",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "avijit.rakshit@tarsons.com",
    linkedin_id: "https://in.linkedin.com/in/avijit-rakshit-15073318a",
    phone_number: 9997812017,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Startup",
    entity_name: "vasant masala pvt. ltd.",
    Company_Size: "201-500",
    Industry: "consumer goods",
    Sub_Industry: "fmcg",
    activity_type: "Manufacturing",
    website: "http://www.vasantmasala.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/vasant-masala-pvt-ltd",
    cleaned_boardline_number:
      "'+917926850140 / +912679226109 / +917925621443 / +917925621444",
    branch_type: "branch office",
    address: "",
    City: "ahmedabad",
    State: "gujarat",
    zip_code: 380004,
    Country: "india",
    contact_name: "Nemi Shah",
    job_title: "manager - marketing",
    Department: "marketing & communications",
    Seniority_Level: "middle management",
    email_id: "nemi.shah@vasantmasala.com",
    linkedin_id: "https://in.linkedin.com/in/nemi-shah-57b46361",
    phone_number: 4819022277,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "vasant masala pvt. ltd.",
    Company_Size: "201-500",
    Industry: "consumer goods",
    Sub_Industry: "fmcg",
    activity_type: "Manufacturing",
    website: "http://www.vasantmasala.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/vasant-masala-pvt-ltd",
    cleaned_boardline_number:
      "'+917926850140 / +912679226109 / +917925621443 / +917925621444",
    branch_type: "branch office",
    address: "",
    City: "ahmedabad",
    State: "gujarat",
    zip_code: 380004,
    Country: "india",
    contact_name: "Ripal Oza",
    job_title: "manager - marketing",
    Department: "marketing & communications",
    Seniority_Level: "middle management",
    email_id: "ripal.oza@vasantmasala.com",
    linkedin_id: "https://in.linkedin.com/in/ripal-oza-b882a392",
    phone_number: 2411261577,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "vasant masala pvt. ltd.",
    Company_Size: "201-500",
    Industry: "consumer goods",
    Sub_Industry: "fmcg",
    activity_type: "Manufacturing",
    website: "http://www.vasantmasala.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/vasant-masala-pvt-ltd",
    cleaned_boardline_number:
      "'+917926850140 / +912679226109 / +917925621443 / +917925621444",
    branch_type: "branch office",
    address: "",
    City: "ahmedabad",
    State: "gujarat",
    zip_code: 380004,
    Country: "india",
    contact_name: "Sanjay Chauhan",
    job_title: "manager - marketing",
    Department: "marketing & communications",
    Seniority_Level: "middle management",
    email_id: "sanjay.chauhan@vasantmasala.com",
    linkedin_id: "https://in.linkedin.com/in/sanjay-chauhan-580b50221",
    phone_number: 5153165938,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "alkem laboratories pvt ltd",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.alkemlabs.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/alkem-laboratories-ltd",
    cleaned_boardline_number: "'+912249186000 / +912249186060 / +912239829999",
    branch_type: "branch office",
    address:
      "Devashish Building, Alkem House, Senapati Bapat Road, Lower Parel, Mumbai - 400013.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400013,
    Country: "india",
    contact_name: "Omkar Debashis",
    job_title: "manager - marketing",
    Department: "marketing & communications",
    Seniority_Level: "middle management",
    email_id: "omkar.debashis@alkemlabs.com",
    linkedin_id: "https://in.linkedin.com/in/omkar-debashis-37b00a20",
    phone_number: 3723562216,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "alkem laboratories pvt ltd",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.alkemlabs.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/alkem-laboratories-ltd",
    cleaned_boardline_number: "'+912249186000 / +912249186060 / +912239829999",
    branch_type: "branch office",
    address:
      "Devashish Building, Alkem House, Senapati Bapat Road, Lower Parel, Mumbai - 400013.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400013,
    Country: "india",
    contact_name: "S Purushotham",
    job_title: "general manager - information technology",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "s.purushotham@alkemlabs.com",
    linkedin_id: "https://in.linkedin.com/in/s-purushotham-a909093b",
    phone_number: 4731566319,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "alkem laboratories pvt ltd",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.alkemlabs.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/alkem-laboratories-ltd",
    cleaned_boardline_number: "'+912249186000 / +912249186060 / +912239829999",
    branch_type: "branch office",
    address:
      "Devashish Building, Alkem House, Senapati Bapat Road, Lower Parel, Mumbai - 400013.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400013,
    Country: "india",
    contact_name: "ABHIJIT P",
    job_title: "manager - product",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "abhijit.p@alkemlabs.com",
    linkedin_id: "https://in.linkedin.com/in/abhijit-p-b31417109",
    phone_number: 5097996211,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "alkem laboratories pvt ltd",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.alkemlabs.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/alkem-laboratories-ltd",
    cleaned_boardline_number: "'+912249186000 / +912249186060 / +912239829999",
    branch_type: "branch office",
    address:
      "Devashish Building, Alkem House, Senapati Bapat Road, Lower Parel, Mumbai - 400013.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400013,
    Country: "india",
    contact_name: "Rucha Thanekar",
    job_title: "manager - product",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "rucha.thanekar@alkemlabs.com",
    linkedin_id: "https://in.linkedin.com/in/rucha-thanekar-a73219147",
    phone_number: 9739067331,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "alkem laboratories pvt ltd",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.alkemlabs.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/alkem-laboratories-ltd",
    cleaned_boardline_number: "'+912249186000 / +912249186060 / +912239829999",
    branch_type: "branch office",
    address:
      "Devashish Building, Alkem House, Senapati Bapat Road, Lower Parel, Mumbai - 400013.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400013,
    Country: "india",
    contact_name: "Avani Nishar",
    job_title: "manager - product (group)",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "avani.nishar@alkemlabs.com",
    linkedin_id: "https://in.linkedin.com/in/avani-nishar-9b783111",
    phone_number: 8253978691,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "alkem laboratories pvt ltd",
    Company_Size: "10001 & above",
    Industry: "Health Care & Life Sciences",
    Sub_Industry: "Pharmaceuticals",
    activity_type: "Manufacturing",
    website: "http://www.alkemlabs.com",
    company_linkedin_url:
      "https://in.linkedin.com/company/alkem-laboratories-ltd",
    cleaned_boardline_number: "'+912249186000 / +912249186060 / +912239829999",
    branch_type: "branch office",
    address:
      "Devashish Building, Alkem House, Senapati Bapat Road, Lower Parel, Mumbai - 400013.",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400013,
    Country: "india",
    contact_name: "Nitesh Bhele",
    job_title: "manager - product (group)",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "nitesh.bhele@alkemlabs.com",
    linkedin_id: "https://in.linkedin.com/in/nitesh-bhele-422b2113",
    phone_number: 1522356327,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "alkraft thermotechnologies private limited",
    Company_Size: "201-500",
    Industry: "automotive",
    Sub_Industry: "automotive",
    activity_type: "Manufacturing",
    website: "http://www.alkraft.com",
    company_linkedin_url: "https://in.linkedin.com/company/alkraft",
    cleaned_boardline_number: "'+914426258750 / +914426258790",
    branch_type: "single location",
    address:
      "Alkraft Thermotechnologies Pvt Ltd 35A & B / 1, Ambattur Industrial Estate Chennai 600058 Tamil Nadu India",
    City: "chennai",
    State: "tamilnadu",
    zip_code: 600058,
    Country: "india",
    contact_name: "R Santhosh Kumar",
    job_title: "manager - information technology",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "r.santhosh.kumar@alkraft.com",
    linkedin_id:
      "https://in.linkedin.com/in/santhoshkumaritinfrastructuremanagement",
    phone_number: 8057211415,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "alkraft thermotechnologies private limited",
    Company_Size: "201-500",
    Industry: "automotive",
    Sub_Industry: "automotive",
    activity_type: "Manufacturing",
    website: "http://www.alkraft.com",
    company_linkedin_url: "https://in.linkedin.com/company/alkraft",
    cleaned_boardline_number: "'+914426258750 / +914426258790",
    branch_type: "single location",
    address:
      "Alkraft Thermotechnologies Pvt Ltd 35A & B / 1, Ambattur Industrial Estate Chennai 600058 Tamil Nadu India",
    City: "chennai",
    State: "tamilnadu",
    zip_code: 600058,
    Country: "india",
    contact_name: "Md Azam",
    job_title: "manager - information technology",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "md.azam@alkraft.com",
    linkedin_id: "https://in.linkedin.com/in/md-azam-538695a",
    phone_number: 7495461652,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "comsol private limited",
    Company_Size: "201-500",
    Industry: "it & communication",
    Sub_Industry: "it software & programming",
    activity_type: "Manufacturing",
    website: "http://www.comsol.com",
    company_linkedin_url: "https://www.linkedin.com/company/comsol-inc-",
    cleaned_boardline_number:
      "'+914773842400 / +914684129510 / +918225472343 / +912122129804 / +916567421250 / +916567421440 / +918067383600 / +917812733322 / +914684129500 / +918040923856",
    branch_type: "single location",
    address:
      "Comsol Multiphysics Pvt. Ltd. Phoenix Pinnacle, No 46, 3Rd Floor, Ulsoor Road Bengaluru - 560042 India",
    City: "bengaluru",
    State: "karnataka",
    zip_code: 560042,
    Country: "india",
    contact_name: "Aditi Karandikar",
    job_title: "manager - marketing",
    Department: "marketing & communications",
    Seniority_Level: "middle management",
    email_id: "aditi.karandikar@comsol.com",
    linkedin_id: "https://in.linkedin.com/in/aditi-karandikar-8679b813",
    phone_number: 6096996749,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "leap india private limited",
    Company_Size: "201-500",
    Industry: "logistics & transportation",
    Sub_Industry: "freight & logistics",
    activity_type: "Service Provider",
    website: "http://www.leapindia.net",
    company_linkedin_url: "https://in.linkedin.com/company/leapindiaofficial",
    cleaned_boardline_number: "'+912228858700",
    branch_type: "branch office",
    address:
      "Address 302, Ruby Crescent Business Boulevard, Ashok Nagar, Kandivali ( E ), Mumbai, Maharashtra - 400101, India",
    City: "mumbai",
    State: "maharashtra",
    zip_code: 400101,
    Country: "india",
    contact_name: "Dhanraj Kotian",
    job_title: "senior manager - information technology",
    Department: "information technology",
    Seniority_Level: "senior management",
    email_id: "dhanraj.kotian@leapindia.net",
    linkedin_id: "https://in.linkedin.com/in/dhanraj-kotian-84109116",
    phone_number: 3818369878,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "machine tools india private limited",
    Company_Size: "201-500",
    Industry: "heavy & industrial machinery",
    Sub_Industry: "industrial machinery",
    activity_type: "Manufacturing",
    website: "http://www.saibabamachines.in",
    company_linkedin_url:
      "https://in.linkedin.com/company/machine-tools-india-limited",
    cleaned_boardline_number:
      "'+912227683584 / +919769281000 / +919820155195 / +912227683586 / +912227683585 / +919769081000",
    branch_type: "branch office",
    address:
      "Address Saibaba Machine Tools ( India ) Pvt. Ltd. Plot No. D - 182 / 1, D - 182 / 2, T. T. C. Industrial Area, Behind London Pilsner, Nerul East, Shiravane, Navi Mumbai, Maharashtra 400706, India",
    City: "navi mumbai",
    State: "maharashtra",
    zip_code: 400706,
    Country: "india",
    contact_name: "Narendra Chukka",
    job_title: "manager - information technology",
    Department: "information technology",
    Seniority_Level: "middle management",
    email_id: "narendra.chukka@saibabamachines.in",
    linkedin_id: "https://in.linkedin.com/in/narendra-chukka-aa9a9088",
    phone_number: 5802361033,
    profiling_status: "STDM",
  },
  {
    Firmographics: "Digital Native",
    entity_name: "mack pharmatech pvt ltd",
    Company_Size: "201-500",
    Industry: "energy & environment",
    Sub_Industry: "environment",
    activity_type: "Service Provider",
    website: "",
    company_linkedin_url: "https://in.linkedin.com/company/mack-pharmatech",
    cleaned_boardline_number: "",
    branch_type: "branch office",
    address:
      "Address : B - 48, Malegaon Midc, Sinnar Dist : Nashik - 422113 Maharashtra, India",
    City: "nashik",
    State: "maharashtra",
    zip_code: 422113,
    Country: "india",
    contact_name: "Harshal Ghoge",
    job_title: "head (marketing)",
    Department: "marketing & communications",
    Seniority_Level: "senior management",
    email_id: "harshal.ghoge@mackpharmatech.com",
    linkedin_id: "https://in.linkedin.com/in/harshal-ghoge-9885a312",
    phone_number: 4908647112,
    profiling_status: "Partial Profiled",
  },
  {
    Firmographics: "Startup",
    entity_name: "nitiraj engineering private limited",
    Company_Size: "1001-5000",
    Industry: "Electronics & Electrical",
    Sub_Industry: "Electrical Equipments & Components",
    activity_type: "Manufacturing",
    website: "",
    company_linkedin_url:
      "https://in.linkedin.com/company/nitiraj-engineers-ltd.",
    cleaned_boardline_number: "",
    branch_type: "headquarters",
    address:
      "Corporate Office And Works : J25 / 26 Midc Awdhan, Dhule - 424006 ( Maharashtra ).",
    City: "dhule",
    State: "maharashtra",
    zip_code: 424006,
    Country: "india",
    contact_name: "Ajay Bhatwal",
    job_title: "vice president - marketing",
    Department: "marketing & communications",
    Seniority_Level: "executive management",
    email_id: "ajay.bhatwal@nitiraj.net",
    linkedin_id: "https://in.linkedin.com/in/ajay-bhatwal-90725820",
    phone_number: 5919354879,
    profiling_status: "Partial Profiled",
  },
];

export default denave;
