const test=[
    {
        "created_date":"",
        "modified_date":"",
        "id":1,
        "name":"Series 1",
        "industry":[
            { 
              "id":1,
              "name":"IT & Communication",
              "subindustry":[
                {
                    "name":"BPO",
                },
                {
                    "name":"sss",
                },
                {
                    "name":"ssss",
                }
              ]
            },
            {
                "id":2,
                "name":"Manufacture",
                "subindustry":[
                    {
                        "name":"xx",
                    },
                    {
                        "name":"xxx",
                    },
                    {
                        "name":"xxxx",
                    }
                  ]
            }, 
            {
                "id":3,
                "name":"BPO",
                "subindustry":[
                    {
                        "name":"xx",
                    },
                    {
                        "name":"xxx",
                    },
                    {
                        "name":"xxxx",
                    }
                  ]
            },          
        ],
        "size":2
    },
    {
        "created_date":"",
        "modified_date":"",
        "id":2,
        "name":"Series 2",
        "industry":[
            { 
              "id":1,
              "name":"IT & Communication",
              "subindustry":[
                {
                    "name":"ss",
                },
                {
                    "name":"sss",
                },
                {
                    "name":"ssss",
                }
              ]
            },
            {
                "id":2,
                "name":"Manufacture",
                "subindustry":[
                    {
                        "name":"xx",
                    },
                    {
                        "name":"xxx",
                    },
                    {
                        "name":"xxxx",
                    }
                  ]
            },          
        ],
        "size":5
    },
    {
        "created_date":"",
        "modified_date":"",
        "id":3,
        "name":"Series 3",
        "industry":[
            { 
              "id":1,
              "name":"IT & Communication",
              "subindustry":[
                {
                    "name":"ss",
                },
                {
                    "name":"sss",
                },
                {
                    "name":"ssss",
                }
              ]
            },
            {
                "id":2,
                "name":"Manufacture",
                "subindustry":[
                    {
                        "name":"xx",
                    },
                    {
                        "name":"xxx",
                    },
                    {
                        "name":"xxxx",
                    }
                  ]
            },          
        ],
        "size":5
    }
]


export default test;